package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/objects"
)

// HealthGate is the resolver for the healthGate field.
func (r *channelResolver) HealthGate(ctx context.Context, obj *ent.Channel) (*ChannelHealthGateStatus, error) {
	if !canReadChannelHealthGate(ctx) {
		return nil, nil
	}
	return channelHealthGateStatus(r.channelService.HealthGate(), r.healthGatePolicy(ctx), obj, r.healthGateConfigResolver(ctx, obj.ID)), nil
}

// ResetChannelHealthGate is the resolver for the resetChannelHealthGate field.
func (r *mutationResolver) ResetChannelHealthGate(ctx context.Context, channelID objects.GUID, actualModel *string) (bool, error) {
	return r.resetChannelHealthGate(ctx, channelID, actualModel)
}
