package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/objects"
)

// PromptWriteCacheVariantCode is the resolver for the promptWriteCacheVariantCode field.
func (r *costItemResolver) PromptWriteCacheVariantCode(ctx context.Context, obj *objects.CostItem) (*objects.PromptWriteCacheVariantCode, error) {
	if obj.PromptWriteCacheVariantCode == "" {
		return nil, nil
	}
	return &obj.PromptWriteCacheVariantCode, nil
}

// CostItem returns CostItemResolver implementation.
func (r *Resolver) CostItem() CostItemResolver { return &costItemResolver{r} }

type costItemResolver struct{ *Resolver }
