package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/shopspring/decimal"
)

// CostPriceMultiplier is the resolver for the costPriceMultiplier field.
func (r *usageLogResolver) CostPriceMultiplier(ctx context.Context, obj *ent.UsageLog) (*decimal.Decimal, error) {
	if obj.TotalCost == nil {
		return nil, nil
	}
	// Records priced before price versions existed, or whose version is gone, were billed without a multiplier.
	one := decimal.NewFromInt(1)
	if obj.CostPriceReferenceID == "" {
		return &one, nil
	}
	loader, ok := ctx.Value(usagePriceLoaderKey{}).(*usagePriceLoader)
	if !ok {
		return nil, fmt.Errorf("usage price loader unavailable")
	}
	multiplier, err := loader.load(ctx, obj.CostPriceReferenceID)
	if err != nil || multiplier != nil {
		return multiplier, err
	}
	return &one, nil
}
