package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/shopspring/decimal"
)

// CostPriceMultiplier is the resolver for the costPriceMultiplier field.
func (r *usageLogResolver) CostPriceMultiplier(ctx context.Context, obj *ent.UsageLog) (*decimal.Decimal, error) {
	if obj.CostPriceReferenceID == "" {
		return nil, nil
	}
	loader, ok := ctx.Value(usagePriceLoaderKey{}).(*usagePriceLoader)
	if !ok {
		return nil, fmt.Errorf("usage price loader unavailable")
	}
	return loader.load(ctx, obj.CostPriceReferenceID)
}
