// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package selfusage

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type SelfUsageCostItem struct {
	ItemCode                    string               `json:"itemCode"`
	PromptWriteCacheVariantCode *string              `json:"promptWriteCacheVariantCode,omitempty"`
	Quantity                    int                  `json:"quantity"`
	Subtotal                    float64              `json:"subtotal"`
	TierBreakdown               []*SelfUsageTierCost `json:"tierBreakdown"`
}

type SelfUsageDailyStat struct {
	Date  string            `json:"date"`
	Usage *SelfUsageSummary `json:"usage"`
}

type SelfUsageMeta struct {
	APIKeyName   string `json:"apiKeyName"`
	APIKeyType   string `json:"apiKeyType"`
	CurrencyCode string `json:"currencyCode"`
	Timezone     string `json:"timezone"`
	MaxRangeDays int    `json:"maxRangeDays"`
}

type SelfUsageModelStat struct {
	Model string            `json:"model"`
	Usage *SelfUsageSummary `json:"usage"`
}

type SelfUsageRequest struct {
	ID                  int                    `json:"id"`
	CreatedAt           time.Time              `json:"createdAt"`
	Model               string                 `json:"model"`
	Status              SelfUsageRequestStatus `json:"status"`
	RequestStatus       string                 `json:"requestStatus"`
	Stream              bool                   `json:"stream"`
	LatencyMs           *int                   `json:"latencyMs,omitempty"`
	FirstTokenLatencyMs *int                   `json:"firstTokenLatencyMs,omitempty"`
	InputTokens         int                    `json:"inputTokens"`
	OutputTokens        int                    `json:"outputTokens"`
	CacheReadTokens     int                    `json:"cacheReadTokens"`
	CacheWriteTokens    int                    `json:"cacheWriteTokens"`
	ReasoningTokens     int                    `json:"reasoningTokens"`
	TotalTokens         int                    `json:"totalTokens"`
	Cost                *float64               `json:"cost,omitempty"`
	CostItems           []*SelfUsageCostItem   `json:"costItems"`
	CostMultiplier      *float64               `json:"costMultiplier,omitempty"`
	CostMultiplierMixed bool                   `json:"costMultiplierMixed"`
	UsageRecords        int                    `json:"usageRecords"`
	UnpricedRecords     int                    `json:"unpricedRecords"`
}

type SelfUsageRequestPage struct {
	Items    []*SelfUsageRequest `json:"items"`
	Page     int                 `json:"page"`
	PageSize int                 `json:"pageSize"`
	Total    int                 `json:"total"`
}

type SelfUsageStats struct {
	Start  string                `json:"start"`
	End    string                `json:"end"`
	Totals *SelfUsageSummary     `json:"totals"`
	Models []*SelfUsageModelStat `json:"models"`
	Daily  []*SelfUsageDailyStat `json:"daily"`
}

// 用量汇总；cost 在 usageRecords=0 时为 0，全部未定价时为 null，否则为已知费用之和
type SelfUsageSummary struct {
	SuccessRequests  int      `json:"successRequests"`
	FailedRequests   int      `json:"failedRequests"`
	InputTokens      int      `json:"inputTokens"`
	OutputTokens     int      `json:"outputTokens"`
	CacheReadTokens  int      `json:"cacheReadTokens"`
	CacheWriteTokens int      `json:"cacheWriteTokens"`
	ReasoningTokens  int      `json:"reasoningTokens"`
	TotalTokens      int      `json:"totalTokens"`
	Cost             *float64 `json:"cost,omitempty"`
	UsageRecords     int      `json:"usageRecords"`
	UnpricedRecords  int      `json:"unpricedRecords"`
}

type SelfUsageTierCost struct {
	UpTo     *int    `json:"upTo,omitempty"`
	Units    int     `json:"units"`
	Subtotal float64 `json:"subtotal"`
}

type SelfUsageRequestStatus string

const (
	SelfUsageRequestStatusSuccess    SelfUsageRequestStatus = "SUCCESS"
	SelfUsageRequestStatusFailed     SelfUsageRequestStatus = "FAILED"
	SelfUsageRequestStatusProcessing SelfUsageRequestStatus = "PROCESSING"
)

var AllSelfUsageRequestStatus = []SelfUsageRequestStatus{
	SelfUsageRequestStatusSuccess,
	SelfUsageRequestStatusFailed,
	SelfUsageRequestStatusProcessing,
}

func (e SelfUsageRequestStatus) IsValid() bool {
	switch e {
	case SelfUsageRequestStatusSuccess, SelfUsageRequestStatusFailed, SelfUsageRequestStatusProcessing:
		return true
	}
	return false
}

func (e SelfUsageRequestStatus) String() string {
	return string(e)
}

func (e *SelfUsageRequestStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SelfUsageRequestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SelfUsageRequestStatus", str)
	}
	return nil
}

func (e SelfUsageRequestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SelfUsageRequestStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SelfUsageRequestStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
