package selfusage

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
)

// SelfUsageMeta is the resolver for the selfUsageMeta field.
func (r *queryResolver) SelfUsageMeta(ctx context.Context) (*SelfUsageMeta, error) {
	meta, err := r.selfUsage.Meta(ctx)
	if err != nil {
		return nil, err
	}
	return &SelfUsageMeta{
		APIKeyName: meta.APIKeyName, APIKeyType: meta.APIKeyType,
		CurrencyCode: meta.CurrencyCode, Timezone: meta.Timezone,
		MaxRangeDays: meta.MaxRangeDays,
	}, nil
}

// SelfUsageStats is the resolver for the selfUsageStats field.
func (r *queryResolver) SelfUsageStats(ctx context.Context, start string, end string) (*SelfUsageStats, error) {
	if err := validateRange(start, end); err != nil {
		return nil, err
	}
	stats, err := r.selfUsage.Stats(ctx, start, end)
	if err != nil {
		return nil, err
	}
	models := make([]*SelfUsageModelStat, 0, len(stats.Models))
	for _, item := range stats.Models {
		models = append(models, &SelfUsageModelStat{Model: item.Model, Usage: toSummary(item.Usage)})
	}
	daily := make([]*SelfUsageDailyStat, 0, len(stats.Daily))
	for _, item := range stats.Daily {
		daily = append(daily, &SelfUsageDailyStat{Date: item.Date, Usage: toSummary(item.Usage)})
	}
	return &SelfUsageStats{
		Start: stats.Start, End: stats.End,
		Totals: toSummary(stats.Totals), Models: models, Daily: daily,
	}, nil
}

// SelfUsageRequests is the resolver for the selfUsageRequests field.
func (r *queryResolver) SelfUsageRequests(ctx context.Context, start string, end string, model *string, status *SelfUsageRequestStatus, page *int, pageSize *int) (*SelfUsageRequestPage, error) {
	if err := validateRange(start, end); err != nil {
		return nil, err
	}
	requestedPage, requestedSize := 1, 20
	if page != nil {
		requestedPage = *page
	}
	if pageSize != nil {
		requestedSize = *pageSize
	}
	if requestedPage < 1 || requestedSize < 1 || requestedSize > 100 {
		return nil, fmt.Errorf("invalid_page: page must be positive and pageSize must be between 1 and 100")
	}
	filterStatus := ""
	if status != nil {
		filterStatus = string(*status)
	}
	result, err := r.selfUsage.Requests(ctx, start, end, model, filterStatus, requestedPage, requestedSize)
	if err != nil {
		return nil, err
	}
	items := make([]*SelfUsageRequest, 0, len(result.Items))
	for _, item := range result.Items {
		items = append(items, toRequest(item))
	}
	return &SelfUsageRequestPage{Items: items, Page: result.Page, PageSize: result.PageSize, Total: result.Total}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
